# validate all commits, and ignore the PR title
commitsOnly: true

# Require at least one commit to be valid instead of validating all commits
anyCommit: true

# Allow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns")
allowMergeCommits: true

# Allow use of Revert commits (eg on github: "Revert "feat: ride unicorns"")
allowRevertCommits: true
