export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_EMAIL_ERROR = "SET_EMAIL_ERROR";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";
export const SET_TEXT_FIELD = "SET_TEXT_FIELD";
export const SET_TOKEN = "SET_TOKEN";
export const SET_GIFT_CODE = "SET_GIFT_CODE";
export const RESET_LOGIN_FORM = "RESET_LOGIN_FORM";
export const SET_CONFIRM_PASSWORD_ERROR =
  "SET_CONFIRM_PASSWORD_ERROR";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const CONFIRM_PASSWORD_USED = "CONFIRM_PASSWORD_USED";
export const SET_VIEW = "SET_VIEW";
export const DISABLE_SUBMIT = "DISABLE_SUBMIT";
export const LOADING = "LOADING";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";
export const SUBSCRIBE = "CREATE_SUBSCRIPTION";
export const HANDLE_PAYPAL_SUBSCRIPTION =
  "HANDLE_PAYPAL_SUBSCRIPTION";
export const DISABLE_COUPON_BUTTON = "DISABLE_COUPON_BUTTON";
export const APPLY_COUPON_CODE = "APPLY_COUPON_CODE";
export const SET_PERCENT_OFF = "SET_PERCENT_OFF";
export const SET_COUPON = "SET_COUPON";
export const SET_COUPON_ERROR = "SET_COUPON_ERROR";
export const UPDATE_COUPON_CODE = "UPDATE_COUPON_CODE";
export const SHOW_COUPON_FIELD = "SHOW_COUPON_FIELD";
export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const HANDLE_REGISTRATION = "HANDLE_REGISTRATION";
export const DISABLE_LOGIN_BUTTON = "DISABLE_LOGIN_BUTTON";
export const DISABLE_REGISTRATION_BUTTON =
  "DISABLE_REGISTRATION_BUTTON";
export const HANDLE_USER_UPDATE = "HANDLE_USER_UPDATE";
export const DISABLE_USER_UPDATE_BUTTON =
  "DISABLE_USER_UPDATE_BUTTON";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_PHONE = "SET_PHONE";
export const SET_ADDRESS_ID = "SET_ADDRESS_ID";
export const SET_PRODUCT_AND_PLAN = "SET_PRODUCT_AND_PLAN";
export const SET_SUBSCRIPTION_TO_RENEW = "SET_SUBSCRIPTION_TO_RENEW";
export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_STATES = "SET_STATES";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const SET_USER_LOADED = "SET_USER_LOADED";
export const SET_UPDATED_PRICE = "SET_UPDATED_PRICE";
export const SET_CAN_MAKE_PAYMENT = "SET_CAN_MAKE_PAYMENT";
export const SET_PAYMENT_REQUEST = "SET_PAYMENT_REQUEST";
export const INIT_CONTAINER = "INIT_CONTAINER";
export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const HANDLE_REMOVE_PRODUCT = "HANDLE_REMOVE_PRODUCT";
export const SET_ORDER = "SET_ORDER";
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
export const SET_SELECT = "SET_SELECT";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const SET_CONFIRM_NEW_PASSWORD = "SET_CONFIRM_NEW_PASSWORD";
export const VALIDATE_PASSWORD = "VALIDATE_PASSWORD";
export const VALIDATE_NEW_PASSWORD = "VALIDATE_NEW_PASSWORD";
export const VALIDATE_CONFIRM_NEW_PASSWORD =
  "VALIDATE_CONFIRM_NEW_PASSWORD";
export const VALIDATE_FIELD = "VALIDATE_FIELD";
export const RESET_FIELD_ERROR = "RESET_FIELD_ERROR";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_NEW_PASSWORD_ERROR = "RESET_NEW_PASSWORD_ERROR";
export const RESET_CONFIRM_NEW_PASSWORD_ERROR =
  "RESET_CONFIRM_NEW_PASSWORD_ERROR";
export const SHOW_ALERT = "SHOW_ALERT";
