export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_EMAIL_ERROR = "SET_EMAIL_ERROR";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";
export const RESET_LOGIN_FORM = "RESET_LOGIN_FORM";
export const SET_CONFIRM_PASSWORD_ERROR = "SET_CONFIRM_PASSWORD_ERROR";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const CONFIRM_PASSWORD_USED = "CONFIRM_PASSWORD_USED";
