export const SET_EMAIL = "SET_EMAIL";
export const SET_USERNAME = "SET_USERNAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_EMAIL_ERROR = "SET_EMAIL_ERROR";
export const SET_USERNAME_ERROR = "SET_USERNAME_ERROR";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";
export const SET_FIRST_NAME_ERROR = "SET_FIRST_NAME_ERROR";
export const SET_LAST_NAME_ERROR = "SET_LAST_NAME_ERROR";
export const SET_PHONE_ERROR = "SET_PHONE_ERROR";
export const SET_TEXT_FIELD = "SET_TEXT_FIELD";
export const SET_DATE_OF_BIRTH = "SET_DATE_OF_BIRTH";
export const SET_MONTH = "SET_MONTH";
export const SET_YEAR = "SET_YEAR";
export const SET_TOKEN = "SET_TOKEN";
export const SET_GIFT_CODE = "SET_GIFT_CODE";
export const RESET_LOGIN_FORM = "RESET_LOGIN_FORM";
export const SET_CONFIRM_PASSWORD_ERROR =
  "SET_CONFIRM_PASSWORD_ERROR";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const CONFIRM_PASSWORD_USED = "CONFIRM_PASSWORD_USED";
export const SET_VIEW = "SET_VIEW";
export const DISABLE_SUBMIT = "DISABLE_SUBMIT";
export const LOADING = "LOADING";
export const SKELETON_LOADER = "SKELETON_LOADER";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";
export const SUBSCRIBE = "CREATE_SUBSCRIPTION";
export const HANDLE_PAYPAL_SUBSCRIPTION =
  "HANDLE_PAYPAL_SUBSCRIPTION";
export const HANDLE_APPLEPAY_SUBSCRIPTION =
  "HANDLE_APPLEPAY_SUBSCRIPTION";
export const DISABLE_COUPON_BUTTON = "DISABLE_COUPON_BUTTON";
export const APPLY_COUPON_CODE = "APPLY_COUPON_CODE";
export const REMOVE_APPLIED_COUPON = "REMOVE_APPLIED_COUPON";
export const SET_PERCENT_OFF = "SET_PERCENT_OFF";
export const SET_COUPON = "SET_COUPON";
export const SET_COUPON_ERROR = "SET_COUPON_ERROR";
export const UPDATE_COUPON_CODE = "UPDATE_COUPON_CODE";
export const SHOW_COUPON_FIELD = "SHOW_COUPON_FIELD";
export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const HANDLE_PASSWORDLESS_LOGIN = "HANDLE_PASSWORDLESS_LOGIN";
export const HANDLE_SOCIAL_LOGIN = "HANDLE_SOCIAL_LOGIN";
export const HANDLE_REGISTRATION = "HANDLE_REGISTRATION";
export const HANDLE_SUBSCRIPTION_FREE_PLAN =
  "HANDLE_SUBSCRIPTION_FREE_PLAN";
export const DISABLE_LOGIN_BUTTON = "DISABLE_LOGIN_BUTTON";
export const DISABLE_PASSWORDLESS_LOGIN_BUTTON =
  "DISABLE_PASSWORDLESS_LOGIN_BUTTON";
export const DISABLE_REGISTRATION_BUTTON =
  "DISABLE_REGISTRATION_BUTTON";
export const HANDLE_USER_UPDATE = "HANDLE_USER_UPDATE";
export const DISABLE_USER_UPDATE_BUTTON =
  "DISABLE_USER_UPDATE_BUTTON";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_START_DATE = "SET_START_DATE";
export const SET_GIFT_MESSAGE = "SET_GIFT_MESSAGE";
export const SET_PHONE = "SET_PHONE";
export const SET_TIN = "SET_TIN";
export const SET_ADDRESS_ID = "SET_ADDRESS_ID";
export const SET_PRODUCT_AND_PLAN = "SET_PRODUCT_AND_PLAN";
export const SET_SUBSCRIPTION_TO_RENEW = "SET_SUBSCRIPTION_TO_RENEW";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FETCH = "GET_COUNTRIES_FETCH";
export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS";
export const GET_STATES_FETCH = "GET_STATES_FETCH";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const SET_USER_LOADED = "SET_USER_LOADED";
export const SET_UPDATED_PRICE = "SET_UPDATED_PRICE";
export const SET_TAX_AMOUNT = "SET_TAX_AMOUNT";
export const SET_CAN_MAKE_PAYMENT = "SET_CAN_MAKE_PAYMENT";
export const SET_PAYMENT_REQUEST = "SET_PAYMENT_REQUEST";
export const INIT_CONTAINER = "INIT_CONTAINER";
export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const HANDLE_REMOVE_PRODUCT = "HANDLE_REMOVE_PRODUCT";
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
export const SET_SELECT = "SET_SELECT";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const SET_CONFIRM_NEW_PASSWORD = "SET_CONFIRM_NEW_PASSWORD";
export const VALIDATE_PASSWORD = "VALIDATE_PASSWORD";
export const VALIDATE_NEW_PASSWORD = "VALIDATE_NEW_PASSWORD";
export const VALIDATE_CONFIRM_NEW_PASSWORD =
  "VALIDATE_CONFIRM_NEW_PASSWORD";
export const VALIDATE_FIELD = "VALIDATE_FIELD";
export const RESET_FIELD_ERROR = "RESET_FIELD_ERROR";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_NEW_PASSWORD_ERROR = "RESET_NEW_PASSWORD_ERROR";
export const RESET_CONFIRM_NEW_PASSWORD_ERROR =
  "RESET_CONFIRM_NEW_PASSWORD_ERROR";
export const SHOW_ALERT = "SHOW_ALERT";
export const SELECT_ADDRESS = "SELECT_ADDRESS";
export const SELECT_BILLING_ADDRESS = "SELECT_BILLING_ADDRESS";
export const LOAD_ADDRESSES = "LOAD_ADDRESSES";
export const SELECT_VIEW = "SELECT_VIEW";
export const SET_CROP = "SET_CROP";
export const SET_ZOOM = "SET_ZOOM";
export const CHANGE_IMAGE_FILE = "CHANGE_IMAGE_FILE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const CROP_COMPLETE = "CROP_COMPLETE";
export const SET_IMAGE_SRC = "SET_IMAGE_SRC";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const SELECT_PAYMENT_METHOD = "SELECT_PAYMENT_METHOD";
export const LOAD_PAYMENT_METHODS = "LOAD_PAYMENT_METHODS";
export const GET_NEWSLETTERS_FETCH = "GET_NEWSLETTERS_FETCH";
export const GET_NEWSLETTERS_SUCCESS = "GET_NEWSLETTERS_SUCCESS";
export const SWITCH_TO_UPDATE = "SWITCH_TO_UPDATE";
export const LINK_TOKEN_VERIFY = "LINK_TOKEN_VERIFY";
export const SET_CANCEL_SUBSCRIPTION_REASON =
  "SET_CANCEL_SUBSCRIPTION_REASON";
export const SET_CANCEL_SUBSCRIPTION_OPTION =
  "SET_CANCEL_SUBSCRIPTION_OPTION";
export const HANDLE_CHECKBOX_CHANGE = "HANDLE_CHECKBOX_CHANGE";
export const SET_IS_DEFAULT_PAYMENT_METHOD =
  "SET_IS_DEFAULT_PAYMENT_METHOD";
export const SET_PAYMENT_METHODS = "SET_PAYMENT_METHODS";
export const SHOW_PAYMENT_METHOD_SELECT =
  "SHOW_PAYMENT_METHOD_SELECT";
export const SET_SUBSCRIPTION_SUSPEND_DATE =
  "SET_SUBSCRIPTION_SUSPEND_DATE";
export const SET_SUBSCRIPTION_FREE_PLAN_ERROR =
  "SET_SUBSCRIPTION_FREE_PLAN_ERROR";
export const SET_EMAILS = "SET_EMAILS";
export const SET_EMAILS_ERROR = "SET_EMAILS_ERROR";
export const HANDLE_LIST_MEMBERS = "HANDLE_LIST_MEMBERS";
export const HANDLE_INVITE_MEMBERS = "HANDLE_INVITE_MEMBERS";
export const HANDLE_REMOVE_MEMBER = "HANDLE_REMOVE_MEMBER";
export const UPDATE_INVITE_BUTTON = "UPDATE_INVITE_BUTTON";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";
export const UPDATE_REMOVE_MEMBER_ID = "UPDATE_REMOVE_MEMBER_ID";
// Dashboard
export const SET_IS_OPEN = "SET_IS_OPEN";
export const SET_ADDRESSES = "SET_ADDRESSES";
export const CLOSE_DASHBOARD = "CLOSE_DASHBOARD";
export const SET_ACTIVE_DASHBOARD_LINK = "SET_ACTIVE_DASHBOARD_LINK";
export const SET_DISABLESUBMIT = "SET_DISABLESUBMIT";
export const CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION";
export const UNSUSPEND_SUBSCRIPTION = "UNSUSPEND_SUBSCRIPTION";
export const REACTIVATE_SUBSCRIPTION = "REACTIVATE_SUBSCRIPTION";
// ========
export const UPDATE_CYBERSOURCE_SESSION_ID =
  "UPDATE_CYBERSOURCE_SESSION_ID";
