#!/usr/bin/env node
/* eslint-disable */

const fs = require("fs");

const gitJokes = [
  "git pull a day keeps the conflicts away",
  "If you have anything staged, commit now or stash forever",
  "git-hg: Don't you know that's poison?",
  "git stash drop: Hey! That stuff's expensive.",
  "Remember to keep your porcelain clean",
  "git-fetch: no training required",
  "Commit early, commit often. A tip for version controlling - not for relationships",
  "Fork by yourself, shame on you. Fork with a friend, now we're getting somewhere.",
  "A branch, a tag, and a reflog walk into a bar. The bartender says, What is this, some sort of rebase?",
  "Why did the commit cross the rebase? To git to the other repo",
  "You can checkout any time you like, but you can never diff.",
  "git-sweep: It's brooms, all the way down.",
  "I kissed a git, and I liked it. I hope my repo don't mind it.",
  "The git that keeps on giving.",
  "git-svn: now you have two problems.",
  "CVS Survivors Meetings are Tuesdays at 9",
  "Beware the HEADless horseman of gitty hollow",
  "Be careful not to step in the git-gui",
  "Ring around the repo, pockets full of plumbing, objects, objects, we all commit.",
  "git-nom --omnom: eats all your tasty code",
  "Gits N' Roses: Now with more git cherry-pop, git freebase, and starring git Slash!",
  "Nurture your git-twigs and they will grow into a full branch",
  "Knock knock. Who's there? Git. Git-who? Sorry, 'who' is not a git command - did you mean 'show'?",
  "git-cherry-pick does not yield actual delicious cherries",
  "Be careful not to remove the branch you're standing on",
  "In Soviet Russia, git commits YOU!",
  "git: Committed for life",
  "git happens",
  "We can't stop here, this is git country!",
  "I bet you thought this was a joke. Nope, git-testa.",
  "May the forks be with you",
  "Wait for the git-beats --drop",
  "git is one byte short of a four-letter word",
  "What we push in life echoes in eternity",
  "git-bisect: The good, the bad and the... uhh... skip",
  "git-stash: The sock drawer of version control",
  "This is not a joke, it's a commit.",
  "git-cherry: the healthier snack",
  "Be careful you don't get lost in gitland!",
  "diff in hell, SVNites!",
  "gitcoin: REWRITE A COMMIT, GO TO JAIL",
  "git off!",
  "Once you go git, you never go back.",
  "This is not the greatest commit in the world, this is just a cherry-pick.",
  "You can store your code in it!",
  "Hadn't been for merge-eyed Joe, Ida been commited long time ago",
  "git commit crim… PUT DOWN THAT GUN AND HANDS UP IN THE AIR!",
  "No, I'm gitticus!",
  "git-blame: ruining friendships since 2006",
  "GitMan: Able to merge 8-headed octopoii in a single command! X-Ray vision of all code history!",
  "In Git we trust!"
];

const message = fs.readFileSync(process.argv[2], "utf8").trim();
if (
  message.match(
    /^\[(FEAT|TEST|CI\/CD|REFACTOR|STYLE|DOCS|FIX|CHORES)\]+ .*/gm
  )
) {
  console.log(
    "\x1b[36m%s\x1b[0m",
    "What a beatiful commit, you deserve a random git joke!",
    "\x1b[0m"
  );

  const randomGitJoke =
    gitJokes[Math.floor(Math.random() * gitJokes.length)];

  console.log(
    "\x1b[33m%s\x1b[40m",
    "\n",
    `        ${randomGitJoke}`,
    "\n",
    "\x1b[0m"
  );
} else if (message.match(/^(Merge branch).*/gm)) {
  console.log(
    "\x1b[36m%s\x1b[0m",
    "Default Merge message is accepted! Happy merging =)",
    "\x1b[0m"
  );
} else if (message.match(/^(v).*/gm)) {
  console.log(
    "\x1b[36m%s\x1b[0m",
    "Default release message is accepted! Happy merging =)",
    "\x1b[0m"
  );
} else {
  console.log(
    "\x1b[1m",
    "You might be perfect, but your commit message is not!",
    "\x1b[0m"
  );

  console.log(
    "\x1b[31m",
    "Please use a message that starts with [FEAT|TEST|CI/CD|REFACTOR|STYLE|DOCS|FIX|CHORES]. And don't forget a space after",
    "\x1b[0m"
  );

  console.log(
    "\x1b[33m",
    "Example:",
    "\x1b[0m",
    "'[FEAT] Added a new feature'"
  );

  process.exit(5);
}
